name: Build and publish Docker image


on:
  push:
    branches: [ main ]


permissions:
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest


  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug github context
      run: |
        echo "github.repository (from env): $GITHUB_REPOSITORY"
        echo "github.repository (from expr): ${{ github.repository }}"
        echo "github.repository_owner: ${{ github.repository_owner }}"

    - name: Set IMAGE_NAME to lowercase
      run: |
        if [ -z "$GITHUB_REPOSITORY" ]; then
          echo "ERROR: GITHUB_REPOSITORY is empty" >&2
          exit 1
        fi
        IMAGE_NAME=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
        echo "Computed IMAGE_NAME=$IMAGE_NAME"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Debug: show IMAGE_NAME env
      run: |
        echo "env.IMAGE_NAME=${IMAGE_NAME:-<empty>}"
        env | sort | grep IMAGE_NAME || true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:latest
          ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
